
export const COUNTRY_CURRENCY_MAP: Record<string, { currency: string; locale: string }> = {
  "USA": { currency: "USD", locale: "en-US" },
  "United States": { currency: "USD", locale: "en-US" },
  "Germany": { currency: "EUR", locale: "de-DE" },
  "France": { currency: "EUR", locale: "fr-FR" },
  "Japan": { currency: "JPY", locale: "ja-JP" },
  "China": { currency: "CNY", locale: "zh-CN" },
  "Canada": { currency: "CAD", locale: "en-CA" },
  "United Kingdom": { currency: "GBP", locale: "en-GB" },
  "Australia": { currency: "AUD", locale: "en-AU" },
  "Switzerland": { currency: "CHF", locale: "de-CH" },
  "India": { currency: "INR", locale: "en-IN" },
  "Brazil": { currency: "BRL", locale: "pt-BR" },
  "Russia": { currency: "RUB", locale: "ru-RU" },
  "South Korea": { currency: "KRW", locale: "ko-KR" },
  "Mexico": { currency: "MXN", locale: "es-MX" },
  "Singapore": { currency: "SGD", locale: "en-SG" },
  "Hong Kong": { currency: "HKD", locale: "zh-HK" },
  "New Zealand": { currency: "NZD", locale: "en-NZ" },
  "South Africa": { currency: "ZAR", locale: "en-ZA" },
  "Sweden": { currency: "SEK", locale: "sv-SE" },
  "Norway": { currency: "NOK", locale: "no-NO" },
  "Denmark": { currency: "DKK", locale: "da-DK" },
  "Poland": { currency: "PLN", locale: "pl-PL" },
  "Turkey": { currency: "TRY", locale: "tr-TR" },
  "Taiwan": { currency: "TWD", locale: "zh-TW" },
  "Thailand": { currency: "THB", locale: "th-TH" },
  "Malaysia": { currency: "MYR", locale: "ms-MY" },
  "Philippines": { currency: "PHP", locale: "en-PH" },
  "Indonesia": { currency: "IDR", locale: "id-ID" },
  "Vietnam": { currency: "VND", locale: "vi-VN" },
  "Israel": { currency: "ILS", locale: "he-IL" },
  "Saudi Arabia": { currency: "SAR", locale: "ar-SA" },
  "United Arab Emirates": { currency: "AED", locale: "ar-AE" },
  "Argentina": { currency: "ARS", locale: "es-AR" },
  "Chile": { currency: "CLP", locale: "es-CL" },
  "Colombia": { currency: "COP", locale: "es-CO" },
  "Egypt": { currency: "EGP", locale: "ar-EG" },
  "Nigeria": { currency: "NGN", locale: "en-NG" },
  "Pakistan": { currency: "PKR", locale: "ur-PK" },
  "Bangladesh": { currency: "BDT", locale: "bn-BD" },
  "Qatar": { currency: "QAR", locale: "ar-QA" },
  "Czech Republic": { currency: "CZK", locale: "cs-CZ" },
  "Hungary": { currency: "HUF", locale: "hu-HU" },
  "Romania": { currency: "RON", locale: "ro-RO" },
  "Ukraine": { currency: "UAH", locale: "uk-UA" },
  "Belgium": { currency: "EUR", locale: "nl-BE" },
  "Netherlands": { currency: "EUR", locale: "nl-NL" },
  "Austria": { currency: "EUR", locale: "de-AT" },
  "Greece": { currency: "EUR", locale: "el-GR" },
  "Portugal": { currency: "EUR", locale: "pt-PT" },
  "Ireland": { currency: "EUR", locale: "en-IE" },
  "Finland": { currency: "EUR", locale: "fi-FI" },
  "Italy": { currency: "EUR", locale: "it-IT" },
  "Spain": { currency: "EUR", locale: "es-ES" },
};

export const getCurrencyInfo = (country: string | null) => {
  const defaultCurrency = { currency: "USD", locale: "en-US" };
  if (!country) return defaultCurrency;
  return COUNTRY_CURRENCY_MAP[country] || defaultCurrency;
};
